export const productD = [
  {
    describtion: "Kask Raven Ipsum",
    price: 1299,
    fileName: "kask1",
    id: 1,
    additionalDesc: "Świetny kask, który zapewni Ci najlepszą ochronę",
    type: "kask",
  },
  {
    describtion: "Kask Raven Aspire",
    price: 850,
    fileName: "kask2",
    id: 2,
    additionalDesc: "Kask na miare twoich oczekiwań",
    type: "kask",
  },
  {
    describtion: "Kask Raven Profile 4",
    price: 539,
    fileName: "kask3",
    id: 3,
    additionalDesc: "Najlepszy w swojej półce cenowej",
    type: "kask",
  },
  {
    describtion: "Gogle 100% Accuri 2",
    price: 299,
    fileName: "gogle1",
    id: 4,
    additionalDesc:
      "Ochrona oczu przed pyłem i poprawa widoczności to najmniejsze zalety tych gogli",
    type: "gogle",
  },
  {
    describtion: "Gogle Shot Iris",
    price: 165,
    fileName: "gogle2",
    id: 5,
    additionalDesc: "Gogle z dodatkową powłoką antifog",
    type: "gogle",
  },
  {
    describtion: "Gogle 100% Accuri 2",
    price: 299,
    fileName: "gogle3",
    id: 6,
    additionalDesc:
      "Ochrona oczu przed pyłem i poprawa widoczności to najmniejsze zalety tych gogli",
    type: "gogle",
  },
  {
    describtion: "Buzzer O'neal",
    price: 599,
    fileName: "buzzer1",
    id: 7,
    additionalDesc: "Przy profesjonalnej jeździe niezbędny element ochrony",
    type: "buzzer",
  },
  {
    describtion: "Buzzer O'neal",
    price: 599,
    fileName: "buzzer2",
    id: 8,
    additionalDesc: "Przy profesjonalnej jeździe niezbędny element ochrony",
    type: "buzzer",
  },
  {
    describtion: "Rękawice O'neal",
    price: 129,
    fileName: "rekawice1",
    id: 9,
    additionalDesc: "Zapewnią Ci najlepszy grip",
    type: "buzzer",
  },
  {
    describtion: "Manetki PROTAPER",
    price: 59,
    fileName: "manetki1",
    id: 10,
    additionalDesc: "Najbardziej rozpoznawalne manetki na świecie",
    type: "manetki",
  },
  {
    describtion: "Manetki PROTAPER",
    price: 59,
    fileName: "manetki2",
    id: 11,
    additionalDesc: "Najbardziej rozpoznawalne manetki na świecie",
    type: "manetki",
  },
  {
    describtion: "Manetki PROTAPER",
    price: 59,
    fileName: "manetki3",
    type: "manetki",
    id: 12,
    additionalDesc: "Najbardziej rozpoznawalne manetki na świecie",
  },
];
